### ISSUE TITLE
Caddy index.php 404 on Windows 10

### ISSUE THREAD

**Issue by Imfero8** [lcavero/blog-ddd-cqrs-ha-example#1]
I'm trying to setup this project on Windows 10, but I get "GET /index.php" 404 on any page I attempt to access.

**Comment by lcavero** [comment]
Hi @Imfero8 , I think the real problem is that the project doesn't have a path "/" configured, as I thought it was of no use. However I think it makes a lot of sense to redirect to the documentation page, instead of giving a 404.
I've uploaded the changes and you should be able to see it now. I have also updated the README.md file to make the installation clearer.

Please let me know if your problem has been solved and thank you very much for the feedback.

**Comment by Imfero8** [comment]
Oh god, sorry for bothering you. I've just quickly built this project and thought there is some url rewriting problem because I've tested few requests that I thought should have worked and logs showed only /index.php 404 but /ping was 200. I understand now, I've should have tested some real routes.

Thanks for a quick reply.
